### ISSUE TITLE
How to build the book

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata-book#4]
Hi,
I would like to read the book during its construction: I would like to "debug" it and (I do not if it will possible) to contribute.

How to build it?

Thank you

**Comment by anjakefala** [comment]
For now, it is all `.md`! =) If you watch the repo (leftmost button in the top-right), you will see whenever we push to it in your github activity feed.

From there, you can directly view pages in github. https://github.com/saulpw/visidata-book/blob/master/colorizers.md
